version: '3.8'

services:
  papu:
    container_name: papu
    image: papu
    ports:
      - 3010:3000
    restart: always
    volumes: # Mount logs to user/papu/logs
      - /var/log/papu:/usr/src/app/logs
    networks:
      - papu-network

  mongo:
    container_name: papudb
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: papuadmin
      MONGO_INITDB_ROOT_PASSWORD: papuadmin
    ports:
      - '27017:27017'
    networks:
      - papu-network
    volumes:
      - papu-data:/data/db

networks:
  papu-network:
    external: true

volumes:
  papu-data:
    external: true
