version: '3.1'
services:
  mongo:
    container_name: papu-mongo
    image: mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: papuadmin
      MONGO_INITDB_ROOT_PASSWORD: papuadmin
    ports:
      - '27017:27017'
