name: CI on Tag

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm install

      - name: Install playwright deps
        run: npx playwright install --with-deps

      - name: Test
        run: npm run test

      - name: Build
        run: npm run build
     
      - name: Deploy
        uses: SamKirkland/FTP-Deploy-Action@4.3.2
        with:
          server: vazacdaniel.com
          local-dir: ./build/
          server-dir: sub/papu.vazacdaniel.com/
          username: papu@vazacdaniel.com
          password: ${{ secrets.FTP_GITHUB_PASS }}
        