name: CI on Tag

on:
  push:
    tags:
      - 'v*.*.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm install

      - name: Install playwright
        run: npm install playwright --with-deps
        
      - name: Test
        run: npm run test

      - name: Build
        run: npm run build
     
    #   - name: Deploy
        