name: Build docker image and push to GitHub docker registry
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install node_modules
        run: npm install

      - name: Grant execute permission to script
        run: chmod +x ./scripts/replace_env.sh
  
      - name: Replace .env variables
        env:
          CONNECTION_STRING: ${{ secrets.CONNECTION_STRING }}
          JWT_SECRET: ${{ secrets.JWT_SECRET }}
        run: ./scripts/replace_env.sh

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      - name: Login to GitHub docker registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ghcr.io/${{ vars.REPO_NAME }}:latest
          cache-from: type=gha
          cache-to: type=gha,mode=max